### ISSUE TITLE
`cbrt` test failure

### ISSUE THREAD

**Issue by derekdreery** [rust-lang-nursery/libm#123]
I ran the random test generator and got this failure:

```
---- cbrt stdout ----
	thread 'cbrt' panicked at 'input: 6222775363775609461, output: 5145423665656058668, expected: 5145423665656058670', tests/cbrt.rs:25:37
```

**Comment by erikdesjardins** [comment]
Hmm, Rust 1.26 and Clang 6 produce equivalent assembly AFAICT ([godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtRiBXAZwNK9Q7FkmEAHIA9ACoA1CTzA8LENIBixTJgBCAZQAi08d2LiuQ8QzwAjcQFsuHFibNcA%2BskvECAOmTTJ4gFIABgBBKWCQv2kAgGZdWPi4hOSk1MT0lIy0zJzsvKyC3ML8otKS8uL40KiAYVQABwBPYnkEAmkIGoBKaVoATj6Y6UtG6W0HaQBZPGRiVC5Gnkw7UmkASRZkL2kQhgZpFuA2rgPMLkxiADdMdC8Iv3uZXUxrhgab6SZ28ZYABTnVkwxhNprN5osCMsuKsNlthtxFGcuHdqjJfhcbHguFw8KgWNIiNJuJhVmgmqsbBg8AAzRqAljoaT4HgtSwcSEEhBYx7SfjUggAdyY6mkWOk1PUmAYo2AxFYkPQq3qc0ueCwjIICC%2BnLFLFQBBmmB5YuVZwu11uPLKlWttoqdpt9qdjpdDtKqJ5AHl6gbMQAvD4jaSaTjCaS6bbYS6sZGPQKhKTSdyeCAADy6PIASpgCIJ8cgOJZMAdUPrZNTpKm4xEImgWDxg7RlBwYgAmaJxaQAdloAFYgn0ACy0ABsMVimgMMk0tA7%2BggtCCrZiAFpF8vxKugl4gjEYkER8veyPe7QupJW5IL0E/PGQnWG5pW8223PpCO%2Bof%2Bl2%2Br2J1Pg3bBIOnXVdQM3Fde0HCDt13fdDxiY9T3PS9r1vGsExkAIuxqWhxGTAg0x6FdpHqIjsJqDtKNQldly8XsOgAPwCXtNBXLsvEGTAVwADlWDi%2BlbPpuJ4ljdC6bZ/FrPEG1%2BIJlGpEdBzfWgvB4rte1/WgeNbQdWx7LsuyCAclPHGJJ0TIJUxialqUwXdMBHVYrKCRTaEcwT0NCB92l%2BJtxSUt81zUnjBz6H8fygvdDNHPp1L/cyAKsyxbMwVsePs5zU0E6klz0m8pO8mTfOfALlOA1Svz08LWyCRde0QwdBxHEdaEHIJ/0s6zbL6alRyCLLByYML0BHZB20K%2B9iukX4YgUwLgJXbcNJ4mJwsGQdDPUlqgk2wcYi7TqZGSuzQsHdwsqLTANNodA%2Bi8qb618wd5vKzttzazTP36dKeJa2hdOauLWyO6QrJs8bLGMgawdTdBB0wBH0HQLsHoiepC3FfMPEI1NXuI2JsDK6Iu00e5pAphgc0rWh6igt9FJekAJVQGwXEsQguAgKz9v7aH%2BYFjNEvEcRYdp%2BmimkIDeyJqCMMiCnpCp9obHZIkKCJBbO1TLwiHZzmICFsnqkV5XpFV9piFeidycp6muGt8zbaV6mLYJR3jYVu32gFD3nbNt2EDxolX2AiAODwDtsEJ6Q2x6JgThbIDWxHWGu1sjPbJt0JnZpaQg6j4CrPT3L%2BZJz3FcrgCCIgAA5Jha9INZa5UHoxU5qUK0mqvFfUXNiHxVNolbScqydk2KewqoQmd8IJ4pmRMwEI4kxxglUGkBiOYIB3naiRWa9QzBJAXAIR5sHpmM7VCIEwTdz1Pkfb7Phqz80C/773mQBQQC5i2LduLBISyiYPsVgjJCZFwpKKE46hQGfAZKKfELFNAwzPPSCBrZWyBCwQg9AX9h4g1bH%2BXBwoAFAMwMAC4TI8CqhxHiPB5sMAcAYNwaQApCAIBLA4fAbB15CmIOgE4mIWDcAIYoakihCCNG2NIAAKr/aQmYAAS2gYGfAYEKRYhdOyamLAAGVUYwrUJwgQ2CYKmPAqsbCnGYAaa4BCLhzGIOWT4lgBDtFnIoXoI5ZEhGRooYAnxhh4ATq4paO49wHiPCeWchI9EEOfsQ8c58uibgJBiU46AODCBOHo6QTiSDrzcR43oSDY6tm2AAdU4ZyYsaxsCNIIdSN4XxAmkVQIoS2mBTTnCAW0vEqxqRFMkSwQgxZ6jzEILQ4sepiDmP2NGVhZxSAEJILw4UowumUOofgOhDDUAVnyUsjg5CQk73NkwBQyBQHSmkAoa4XACGgMpA2TAqYmDIAIHc/JKi1GHLqSU64pEVRqg%2BAKYskjiANnsJYAgcovl1McamSZLBMBAJCWEhcS4hjDJcegAQlgqZcHjogux1CmDI1FO0SwnyADWsiqnFgJUi%2BeURYXws%2BQaBhqpPAcFuaMQkdKND1AKTo/QN5%2BCcm1OsxQmykHAIuAQvZWJcT4jmDwvJqABFCPNooNhEipEEEaP%2BTU7dTEMClZgWyMw8Dou8F/O8lc84F1iJRFydUBblz3orRMAY5iyBcbCuZCzYgqAej3CmEc3xpiiKmcWg4JJ623lzI2PqKaus7OHSOkCYhEzjp8ROocU5p0zhnbOXsq4uqHpkMG3q2WRr7nmSsoMa5BDbicDuDAu5OsjVPdN%2Bca2dgLqLIYb9AIVsrlPAplrizYQrpGzN%2BgR2x2HpOGck7Fb9vntGs%2BI4KpUTde%2BMyC6o05pwmHAuYSOBKR6G6o9bZN0U3aMBRmIBmZzDZim7Naac7zznpWqItdMAClXp4Ypy5zm7zZTIA%2BOMiJvgIJIGuqZxBIckDES%2BwEkO/AgOhmI4h0wEJ/n/GaEBiAduCZM6UepMTwIBVgWUGhpDKU1NqJg9RlSoEseYyEJw8I1wowQwkHCzX4honRBiJHkE4RcSRWgFEqK9HEIuWRCjiwapXhxrjPGBksAISYkFzDhAal5DkrhbGZM1AIPheD6ZpDycU1fSieE2wYKTIWdpZqnkwfuTMxOJx3GavFEUlx2GrwEZ1l/AhcjiCCo3g0X0eAAwhZcfUYUtypQFJOXpwt5SXAuAIKwakPgUSAe7r3GN7QZAEB6DIPDBhKy/srS%2B3RUQoByTXQcdrfkusuLRK2Lod6R4dHI1ECj426sdFmn1qIvxE3NdnpIAhS8eEEk%2BFo8Un7pD%2Bo3oSSDKaOhcDeJxvAdz3nCB9Klgp9ZBBea1AQYTij1D2AYO0MUzBiBUJcd48xwAxm5iwNK7GKZ7NsnaHqFW5mmEikswQ9sy4VzbyJAweoJxPvfYkhTGpmpuEMi89q4UurdurHyYUlxQWGTEYEAwRkRZpCMV7OIVOigliUtcYxaCvjse1LMRYqxHAbHk9cQj1cyOWFo/EfifJGqGQfF4ICw1APuKmmQKqhhwvvH5OAwKIg%2BnfPabmLp7l%2BJaXqDuUwVKXy8lckETQhQ73peKNGfA8nBDtwtUOolMnxBnHlJlwIOXpmbmm%2BLBwUVhImBBfaEMRH4vUc%2BfK8Ma1JBiz5Jd/sTX6PhTfeB2DLwnuUdo7K1XCrZ7EO61QPrHehsn3qxjbukbVkeIC2MsN1OVky0Z2QK3jq48WsMyUu%2BlmX6DYR0W/%2BmQeJixLFFTrvX1KLi5cJA1KD7DanC6PR7kcqMJcnDL7yRDURHvCxq5Id7Jx3lcojZV4CQ9RZPNPwU33RT73vXokXx/k4KLEEU0eiij2OEN%2BFMoG2GXWJ%2BFkNWb8F%2BBSHyiKB%2BYWWacmBIPQosEAoBI2QmT%2BxAK4MBV%2BXy/4Aob8LiV8%2BgMQ5%2BwB62YB461WBwoMm%2BMQNQRcH%2B4624TOY6I2PSOIbw%2BIB%2Bj2OcXYugogXQjAYgvYogpASgogQQEhqAYgmY3A7Q/AggYYZ8MQtAEhBAYgMhIhEASAaAWAuAhAJA5AlANArYjArAoABWbgfAAgQgIgEgU%2BhwigygagGgOg%2BghgpgTgyA5gVgtg9gjgpgfhrgBEPgD0AGUQbozoMRrosRCR8RSRcRboqI0gdQTQhwbQHQ3QvQAwQwQYPwUwMwcwCwSwKw6wmw2wuw%2BwWRFyL25oNwJey2aRzwrw7wjI2oPw/wqAgIwI%2BIoIpREIUIMIVR8IOIaK2IzRM0GIWI9C0uG8xIpIDQdITC%2BAtI7mzI8KVg7IaeXIie7KhygoZC6iEoGgdyICFCioRmqo6o0q7Q3m0gkOhoxoJwvSjRloaRKRiR3xyRPx/xfxgJ7okQLRIJ0g3oSWAYdOowIYOSxYEY0gUYMYzRd4iYKGGYaR2Y/c%2BYhYGmpY7QAKVYqId4NYy4igyArCQObqvGCAXgCAkCOcZJmwlJc6jBPAvC3g9Jea8sPAbSvgPk6sQCbYhWEQM4b4PY/YQ4o4MQqwiYYpYcoEa4OKMEkS8EMSyEF4V4tUD0T4b4H4X460CUkBgEMaip4Eq4UEKpcE0SiEsSKEWpBUJJmEJMuEtmoOxEpE5EQBR6EmMQH%2BEAzErE7EnEMQIk/EnEQkIkYkWOk0vJBo/J00BKhYVMEQnWwEvQakGkWkOkekBkRkJk%2B0qwSU3UdkDkTksMrkrUHkE0d4vWi0qkPEoU60kU%2B0B0PYH48URZXUKUdk6UmUsMOUeU2pk0vwQEnYGZVUQkXYtU9UjUzUrU7Uspx0JZvU/Ug0w0fQo040D0M2i0y0vYq060MQm0XY20I4u0XY%2B0XYS5sMKUmAZ0F0t5GgN0d0O5b0%2Bg%2Ben0AwrUgkjZ/0gMHZIMT%2B4M1IkM0MWU8MiMNwKMaMoQSZRKxYNc8FVMTWNYpMGEfQDgaq5cyFkK/4EcQCSkhWooNsghRIb486VYghFawQm5hKVMxFZA0IvARB/etFBFBAwp7QS6RIXgeAua2AxaHeqYJcZaNFf6fQecehQ60c70IltkgsFMaJ8G9cjczcrc6iXaPaGFtFTaA8LaI8Y8nsGFAGtFUQq2K8BExSW8nMIAGF%2B8FMh8V4x8j878WG18V4t898J8CmT8RoySb8H8mG9l38v8IoACnaFCICYCiCuaEq0CYocCMVjI3iKCaCIhjCZ82CWVeCIVhCL8OVJx2yueKq8xjClI2SrCJwomXCsuvCQSRAOqwi%2BqieZlMgSu0iamiify6ioCWiJwcVgKhiai4C%2BcYSfOPGgutibSDiElUQwuAKUepSXi%2BIo4fiASfCQIHMYSAKES1pCESEcSe2v8eVSSr8qS6SkI8yWScJNu/8L%2BLike0eZS3ibY1StS%2BSDSTSc1MgLSqAbSfCkyXSpw7x/SJuQyIyRqEyUy9isyJACy0gJyKyeVsqLA8qxVuytCWIByRyiiSN5Sh2f2MwAqfmjyeVLy8w7Q%2BB3ygq3VRiAK%2BSS1wKXGtx4KkKeA0KShhYnKiKCSP1sBqK9qmKJw2KkGeKTI9FZwpKjI5KLilKKVNK9KjKzKx1Ro/NHKCKJuiNHNuYJNQqIqYqg1kqx1MqgicqcWCqOyv%2B/NpV2FdVWqTVeqoikVoy0ipq%2BxvVlqG81qkiau9qZWbVTpklFY0lSmHqi4/Md6pMAEu2gaZmlgIaoCYasFfQ7FXgFYd%2BkgVkCa4lqdA4PFHAfFAlQlpaXeudtFUlS6RcGJM8A4tFulOYzaRlSlMgbalGWlKdtFPFQc6S46T45dZFUo5wOl%2BdQ6y6qGHB66CmbFA4hdOaKcFUAAqvovom/jUGOLnXPS6WHBxURbVpmkwYwRUrna1voIXdSOJbXX0KZQOEBiBmBg8RvAdrZXlXBu6YhshnZmhhFu5foDhnhhFoRjXW1ewmFcWLhhNmKECNRo0LRqEvsAxpQpKCxvcZ8JxkblYl8GcMpoJsA7fTVhvDVd4r6R/tJi6cgQpt6UfXhKphTOptwlpug9xpgybnlYZlxtkiZutvYMgBZlqFZjZuiQ5r0E5keq5hYYwgWBzHwt5nlQ8tg2wpTrquLYgX/YA1Fj9XlbFvFrID6FYslpCkUulnKHsFli8KAvylrWEt4gVkViwCVlsCFUHaox0EhrVifDZkRjPX0KfQSCfBAHJMQSfH5EE6OUNm/FAMQJIBRtEw/LNKEwtpfbRTffdIvIHqZkwJtiPjthcHtk/QUZzEdidvUGdqMBdj0u0OLeivYC0DIw9nlTLmcCwjARjtQr9lcgDhwEDpZg/QhuDk8WWKrLwzDnsawHlaLkjoQJ/krDnhcFjtIDjrVekwTo7SToCsLko3lQKDTnTsWIzszkgmzoyACpzszoyrzpcpNULg9SLlLGLlM3vnlVrs9uk/LqTooh1ZCCuKrurviJrk7sWPPniOTUw8bthWblKKMJbnZNbjqHbvgA7v7s7nKpng9Xldvl7pOD7n7s83iTwvLkmKwMnkSBHhvEtWrLHvc%2B0I8/zUWHinsezWjaizi9nl9tQj0xi5/gHfg0HefYhpvXxQ3oK6wamC3q3u3rDF3rZD3q3svavd474%2BfUkwOImNPryJCHPiBgvuMnKFrSvgUxcjVc/n7lvgXjvtM5NLRQNboufv%2BJGgBG4%2BotTSnS46hl/vawBAwYfRKh/o84lD/n/kfQAYppawOKAbotAXa5GomI9iPHgXAdVs4zGjgbVuIOgcQUbABCm06wm4QcQQzsBOQYmxhb47G5oEhr/olD3ImF68wQxKwfRL3ZwWjmdgwqG30HpdLjRYIcIaIaIOIZIdobIWIJRMoQ4cPG2JoUO0NqQHSiAP2H24OBIVITIaQHIaIBIQ7PQFodIb23ALAPoazCU1TGQBQBAGgDYMexcCAMQADOeaQJIm9hcA7BAJYEO6QNI5smIBoaQBezYPap6CwNKO%2B1gOYmwFTCBxzZgF8v5u%2B%2B8tB7sd%2BxIdsgwO%2B9sTYEhyIcwGwDe4oYwFYA7JACIYlmqg7KICuJ6Ju/YcIHQFh2Icu%2B%2B%2Bu5wDwL4KpCnDuB0EYUQGFsuPQOkUe2dtQmoWeEoooVO7u7oYe5e4J6e5QBe1e1bMgBSVYeeQNI%2B1dS%2B2%2B7ux%2B%2BbY0Eh7%2B6zP%2B0AoB8B9p6B1YRB2Z1BzB48nB6mAh5CPpyh2hy0Bh6IBoVh1YSADYcgPh5YIR4bGu3ozJGIBRzEFRyoSIINn2wOyu8O6IKKyOCuIFMp3wr4rBJx/gNxxOxI3UNJyezlz0DUOJzoaQHoSAOsdSKYRAAwAgFu6QMQHVyANF6h/2wx9p%2Bu7oDSBWMxwQKx14OxzeJcCcIl8l8pKl0EulzuCV8ISIXOwu610u4Ox12IJu816QDuzoXR6IK2O16u%2BuzNzO9cNCmqiAIOEAA)), so I think the code is right. Though the baseline musl implementation is probably compiled with GCC?

I then tried adding
```c
#include <inttypes.h>
#include <stdio.h>
int main() {
	union {double f; uint64_t i;} u;
	u.i = 6222775363775609461;
	u.f = cbrt(u.f);
	printf("%" PRId64 "\n", u.i);
	return 0;
}
```
(and `__attribute__ ((noinline))`)
to [the original file](https://git.musl-libc.org/cgit/musl/tree/src/math/cbrt.c), expecting to see different results:
```
$ clang --version
Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
$ clang test.c -o test -O3 && ./test
5145423665656058668
$ gcc test.c -o test -O3 && ./test
5145423665656058668
```
...but it produces the same thing as Rust.
(For posterity, without noinline it gets evaluated at compile time, but does the same thing, as expected.)

I'm not sure what's causing it.

**Comment by vks** [comment]
Floating point arithmetic is [not really deterministic](https://randomascii.wordpress.com/2013/07/16/floating-point-determinism/). There are a lot of reasons why you could get small differences.

**Comment by Schultzer** [comment]
I think we can close this on. this is based on the old test suite.
