### ISSUE TITLE
Testing system

### ISSUE THREAD

**Issue by burrbull** [rust-lang-nursery/libm#156]
Sorry @japaric , but I have question.

As I can remember, you started rework testing system.
1. `cargo run -p input-generator --target x86_64-unknown-linux-musl`  creates input data
2. `cargo run -p musl-generator --target x86_64-unknown-linux-musl`  solves expected results for musl.
3. `cargo run -p newlib-generator` same for newlib.
4. run generated tests
    `cross test --tests --features checked --target $TARGET --release`
But no tests are generated.
These https://github.com/rust-lang-nursery/libm/blob/3559e703795d33e84a91da2a35f2f3baac47e872/shared/src/lib.rs#L148 macro never used, as I can see.

**Comment by alexcrichton** [comment]
I've rearchitected the testing system recently so now a simple `cargo test` should be suffice for running tests, so I'm going to close this.
