### ISSUE TITLE
rustc incorrectly complains libm::F32Ext is unused

### ISSUE THREAD

**Issue by tarcieri** [rust-lang-nursery/libm#158]
Not sure if I should report this as a `libm` bug or a rustc bug as it really seems more like the latter, but I figured I'd start here.

I'm using `libm` on a `no_std` target. Things were going great for awhile, then in the course of refactoring some code, this started happening:

```
error: unused import: `libm::F32Ext`
  --> src/vector.rs:13:5
   |
13 | use libm::F32Ext;
   |     ^^^^^^^^^^^^
```

However that is definitely not the case. If I remove the import from this code, I get the following instead:

```
error[E0599]: no method named `sqrt` found for type `f32` in the current scope
   --> src/vector.rs:100:49
    |
100 |         differences.map(|n| n * n).sum::<f32>().sqrt()
    |                                                 ^^^^
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            `use libm::F32Ext;`

error[E0599]: no method named `sqrt` found for type `f32` in the current scope
   --> src/vector.rs:105:71
    |
105 |         self.iter().map(|n| n.clone().into() * n.into()).sum::<f32>().sqrt()
    |                                                                       ^^^^
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            `use libm::F32Ext;`

error[E0599]: no method named `atan2` found for type `f32` in the current scope
   --> src/vector.rs:252:22
    |
252 |                 (-x).atan2((y * y + z * z).sqrt())
    |                      ^^^^^
...
331 | impl_3axis_vector!(I8x3, i8, "3-axis XYZ vector of `i8` values");
    | ----------------------------------------------------------------- in this macro invocation
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            `use libm::F32Ext;`
```

This does the trick as a workaround:

```
#[allow(unused_imports)]
use libm::F32Ext;
```

...but otherwise this feels like a pathological interaction between rustc's passes for unused imports, and the handling of those primitive methods which are otherwise there in `std`

**Comment by tarcieri** [comment]
I thought for a second this might be because I was doing something wacky like a conditional `extern crate std` which gets pulled in during the tests (rendering the `libm` import unnecessary) but nope, this is 100% `no_std` code and there is no `extern crate std` to be found.

**Comment by tarcieri** [comment]
My best guess is rustc is linking `std` during tests implicitly (I used to have to do this explicitly... did that change at some point or am I just confused?)

So I think `libm` is needed when performing actual `no_std` builds, but the tests are using the `std` imps of these functions.

**Comment by alexcrichton** [comment]
I suspect that this isn't a bug with this library moreso a bug with rustc and/or configuration locally, so I'm going to close this.
