### ISSUE TITLE
New release on crates.io

### ISSUE THREAD

**Issue by Schultzer** [rust-lang-nursery/libm#167]
Hi guys,

Thanks for fixing the tests. Are there planned for a new release on crates.io?

I just pulled down from master and all test are green for me, so it seams that the issue with overflow check is gone #4 ?

A new release would make it possible for num-trait to move forward with impl no_std for Float.

**Comment by alexcrichton** [comment]
ping @japaric, would you be up for adding me as an owner on crates.io to publish?

**Comment by japaric** [comment]
@alexcrichton I have just sent you an invite

**Comment by alexcrichton** [comment]
Awesome, thanks @japaric, published now!
