### ISSUE TITLE
Functions returning tuples should use out-params like C

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/libm#199]
The functions returning tuples are ABI incompatible with C. They should use out parameters. It is unclear whether the type of the output parameters should be `*mut T`, `&mut T`, `NonNull<T>`, `&Cell<T>`, `Option<&mut T>`, etc.

We should discuss the pros/cons of the alternatives before choosing a solution.

**Comment by danielhenrymantilla** [comment]
The most general pattern would be to use `*mut T` in conjunction with `ptr::write` to "return" the values.

Something better expressing the nullable semantics would be `Option<&mut MaybeUninit<T>>`:

  - either a `NULL` pointer,

  - or a valid (dereferenceable) unaliased pointer to an uninit value (in the unlikely worst case where `mem::needs_drop::<T>()`, if C were to provide a pointer to an already init value, then such value would be overwritten without being dropped, as would be expected from within a C API).

But most often than not, `T` will be not only `Copy`, but numeric. So, assuming uninitialised numeric types are valid (see https://github.com/rust-lang/unsafe-code-guidelines/issues/71), then the `MaybeUninit` part could be dropped.

**Comment by gnzlbg** [comment]
@danielhenrymantilla you have proposed many options (`Option<&mut MaybeUninit<T>>`, `&Cell<T>`, `*mut T`). Why would you pick any of those over `NonNull<T>` ?

**Comment by alexcrichton** [comment]
I'm going to close this since I don't think that this is how we want to define these functions. This is just a C-ism of how to return multiple values and we don't need to carry that baggage in the implementation of these intrinsics. Only at the C ABI boundary (if we add one) do we need to use out-parameters.
