### ISSUE TITLE
Pin a stable version in CI

### ISSUE THREAD

**Issue by Lokathor** [rust-lang-nursery/libm#213]
Would it be possible to pin a particular stable version in CI and then have any bump in the minimum stable version required also be a breaking change for the library?

This is a potentially very foundational library and it's also the kind of thing that people who aren't able to update their compiler and are trying to make their own libstd for an arcane target will rely upon. It should attempt to have maximum stability in the versioning.

**Comment by alexcrichton** [comment]
This is something we don't have the resources for at this time. While it's a great goal and no one's going to disagree with it it requires a lot of maintenance and work. The primary purpose of this repository is to be a source of intrinsics for supported targets of rust-lang/rust, and while we can have reasonable stable requirements on the compiler the rust-lang/rust use case comes first.

**Comment by Lokathor** [comment]
I'm not entirely clear on how it's such a large a large amount of work.

You just pin 1.36 (current stable) now, and then if CI gives a build failure because a PR requires a newer stable version you increase the crate's stable version and make it a breaking version change, or you adjust the code to avoid the break. Either way it's just a small extra check in each PR's normal workflow, so the effort should stay small and manageable.

Since the crate has only one dev dependency and one build dependency, both specified down to an exact patch release, it seems rather simple to keep track of those as well.

To be clear, I am _not_ requesting that you never increase the minimum rust version. I would just like that you reflect any increased `rustc` requirements in the crate's version number when the minimum `rustc` version goes up.

If it is a great burden in some way I'm not seeing then I'm willing to help out with my time to alleviate the workload problem.

**Comment by alexcrichton** [comment]
Unfortunately this is exactly why it's so much work. It ends up being an endless debate about what version to support, all PRs have to consider it, it'll eventually break and get raised and then cause all sorts of hullabaloo. I maintain dozens of crates on crates.io and every single time a minimum version requirement is added to CI it causes headaches and issues. 

I'm the main person maintaining this crate right now, but I don't really want to be myself. While that's the case though I do not have the energy to support this.

**Comment by Lokathor** [comment]
Well, if you're interested in having a second maintainer I'll happily sign on.

I've recently begun the (slow) process of developing a core-only linear algebra / graphics math lib, so my fate is tied to your fate either way at this point.

**Comment by alexcrichton** [comment]
Yeah if you're willing to help out with reviews and such, that'd be great! Would you be willing to do things like reviewing PRs, helping users who run into issues, etc?

**Comment by Lokathor** [comment]
Yeah I can do that.

The code development itself I don't really have time for because I've got my own [vector lib](https://github.com/Lokathor/hektor) in development as I said. Reviewing and trying to help on issues I can totally do though. I'll start "watching" the repo so I get notifications about it all and then help out as best I can. Feel free to send me any additional on-boarding info via Discord or ping me in any existing issues you want me to see or anything like that.

**Comment by alexcrichton** [comment]
Ok! I've added you as a collaborator of this repo and if you want to send a PR this feel free to do so
